/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.view;
import hotel.controller.controller;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import hotel.model.Administrateur;
import hotel.controller.*;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author DELL
 */
public class adminpage extends javax.swing.JFrame {
public static Administrateur administrateur = new Administrateur("haddad" , "zakaria") ;
    private int selectedRow;
javax.swing.table.TableColumn idColumn;
    /**
     * Creates new form adminpage
     */
      DefaultTableModel model;
      DefaultTableModel modelChambre;
    public adminpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        gestiondereservation = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        gestiondechambre = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        btnadd = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblchambre = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("welcome admin ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel1)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setForeground(new java.awt.Color(0, 204, 204));
        jTabbedPane2.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N

        gestiondereservation.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 204));
        jButton2.setText("accepter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 204, 204));
        jButton3.setText("refuser");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        model = (DefaultTableModel) Reservation.remplirLeTableauDeReservation(administrateur);
        jTable1.setModel(model);
        idColumn = jTable1.getColumnModel().getColumn(6);
        jTable1.removeColumn(idColumn);
        jScrollPane2.setViewportView(jTable1);
        // Créer un éditeur de cellules personnalisé pour la colonne des boutons
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                selectedRow = jTable1.rowAtPoint(e.getPoint());;
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("tableau des demandes de reservation ");

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 204, 204));
        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gestiondereservationLayout = new javax.swing.GroupLayout(gestiondereservation);
        gestiondereservation.setLayout(gestiondereservationLayout);
        gestiondereservationLayout.setHorizontalGroup(
            gestiondereservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestiondereservationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                .addGap(26, 26, 26))
            .addGroup(gestiondereservationLayout.createSequentialGroup()
                .addGroup(gestiondereservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gestiondereservationLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton2)
                        .addGap(53, 53, 53)
                        .addComponent(jButton3)
                        .addGap(45, 45, 45)
                        .addComponent(jButton4))
                    .addGroup(gestiondereservationLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gestiondereservationLayout.setVerticalGroup(
            gestiondereservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestiondereservationLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(gestiondereservationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("gestion des reservation", gestiondereservation);

        gestiondechambre.setBackground(new java.awt.Color(255, 255, 255));
        gestiondechambre.setPreferredSize(new java.awt.Dimension(106, 320));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("numero de la chambre");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("type de la chambre");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("etat de la chambre");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Double", "Triple", "Quadriple" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Non Réservé", "Réservé" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        btnadd.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(0, 204, 204));
        btnadd.setText("add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btndel.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btndel.setForeground(new java.awt.Color(0, 204, 204));
        btndel.setText("del");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        tblchambre.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        tblchambre.setForeground(new java.awt.Color(0, 204, 204));
        modelChambre = Chambre.getALLChambre(administrateur);
        tblchambre.setModel(modelChambre);
        tblchambre.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblchambre);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 204));
        jButton1.setText("modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gestiondechambreLayout = new javax.swing.GroupLayout(gestiondechambre);
        gestiondechambre.setLayout(gestiondechambreLayout);
        gestiondechambreLayout.setHorizontalGroup(
            gestiondechambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestiondechambreLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(gestiondechambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gestiondechambreLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gestiondechambreLayout.createSequentialGroup()
                        .addGroup(gestiondechambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(38, 38, 38)
                        .addGroup(gestiondechambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51)
                .addGroup(gestiondechambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnadd)
                    .addComponent(btndel)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gestiondechambreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        gestiondechambreLayout.setVerticalGroup(
            gestiondechambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gestiondechambreLayout.createSequentialGroup()
                .addGroup(gestiondechambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gestiondechambreLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(gestiondechambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gestiondechambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(gestiondechambreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(gestiondechambreLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("gestion des chambres", gestiondechambre);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 640, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        // TODO add your handling code here:
        if (tblchambre.getSelectedRow()==-1){
        JOptionPane.showMessageDialog(adminpage.this, "select any chambre to delete");
        }
        else {
                System.out.println(tblchambre.getSelectedRow());
 int row = tblchambre.getSelectedRow();
 if(modelChambre.getValueAt(row, 2).toString() == "Réservé") {
             JOptionPane.showMessageDialog(adminpage.this, "Vous Pouvez Pas Supprimer Une Chambre Déja Réservé");

 }
 else {
       Chambre.SupprimerUneChambre(administrateur,modelChambre.getValueAt(row, 0).toString());
               modelChambre.removeRow(tblchambre.getSelectedRow());
        }
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (selectedRow != 0) {
        String idClient = model.getValueAt(selectedRow , 6).toString();
        
       Boolean res = Reservation.accepteruneréservation(
                administrateur, idClient ,
                model.getValueAt(selectedRow, 2).toString()
                , model.getValueAt(selectedRow , 3).toString(),
        model.getValueAt(selectedRow , 4).toString()); 
       if(res) {
                   model.setValueAt("Oui", selectedRow, 5);  

       }
// Mettre à jour la colonne 3 avec "Oui"
        } else {
                    JOptionPane.showMessageDialog(null, "Veuillez sélectionner une Réservation d'abord.");
                }
        
        
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    if (selectedRow != 0) {
          Reservation.refuseruneréservation(administrateur, model.getValueAt(selectedRow, 6).toString());
                    model.setValueAt("Non", selectedRow, 5);  // Mettre à jour la colonne 3 avec "Oui"
                } else {
                    JOptionPane.showMessageDialog(null, "Veuillez sélectionner une Réservation D'abord.");
                }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  Boolean numeroExiste = false;
  // vérifier si il a chosit une ligne
    if (tblchambre.getSelectedRow()==-1){
        JOptionPane.showMessageDialog(adminpage.this, "select any chambre to delete");
        }
    else {

         if(modelChambre.getValueAt(tblchambre.getSelectedRow(), 2) == "Réservé") {
                                     JOptionPane.showMessageDialog(null, "Vous n'avez Pas le droit de modifier une chambre réservé");

         }
         else {
     // vérifier si le numero q'uil a mit  existe deja et vérifier si il a laisse le numero vide
     if(jTextField1.getText().toString().length() != 0 && jTextField1.getText().toString() != modelChambre.getValueAt(tblchambre.getSelectedRow() , 0).toString()) {

         for(int indexRow = 0 ; indexRow < modelChambre.getRowCount() ; indexRow ++) {
             if(indexRow != tblchambre.getSelectedRow()) {
                  Object cellule = modelChambre.getValueAt(indexRow, 0);
    if(cellule.toString().equals(jTextField1.getText().toString())) {
        numeroExiste = true;
        break;
    }
             }
   
}
if(!numeroExiste) {
       // Chambre.ModifierUneChambre(administrateur ,jTextField1.getText() , jComboBox1.getSelectedItem().toString() , jComboBox2.getSelectedItem().toString());
              Chambre.ModifierUneChambre(administrateur , modelChambre.getValueAt(tblchambre.getSelectedRow(), 0).toString()  ,jTextField1.getText().toString() , jComboBox1.getSelectedItem().toString() ,jComboBox2.getSelectedItem().toString()); 

          modelChambre.setValueAt(jTextField1.getText(), tblchambre.getSelectedRow(), 0);
    modelChambre.setValueAt(jComboBox1.getSelectedItem(), tblchambre.getSelectedRow(), 1);
    modelChambre.setValueAt(jComboBox2.getSelectedItem(), tblchambre.getSelectedRow(), 2);
}
     
else {
                        JOptionPane.showMessageDialog(null, "Ce Numéro De Chambre Existe Déja");
}

     }
     else {
    modelChambre.setValueAt(jComboBox1.getSelectedItem(), tblchambre.getSelectedRow(), 1);
    modelChambre.setValueAt(jComboBox2.getSelectedItem(), tblchambre.getSelectedRow(), 2);
                  Chambre.ModifierUneChambre(administrateur , modelChambre.getValueAt(tblchambre.getSelectedRow(), 0).toString()  , modelChambre.getValueAt(tblchambre.getSelectedRow(), 0).toString() , jComboBox1.getSelectedItem().toString() ,jComboBox2.getSelectedItem().toString()); 

     
     }
     }
     
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         if (selectedRow != 0 ) {
                            String idClient = model.getValueAt(selectedRow , 6).toString();

                    Reservation.supprimerUneReservation(administrateur , idClient );
                                        model.removeRow(selectedRow); // Mettre à jour la colonne 3 avec "Oui"

                } else {
                    JOptionPane.showMessageDialog(null, "Veuillez sélectionner une ligne d'abord.");
                }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        Boolean numeroExiste = false;
        if (jTextField1.getText().toString().length() == 0){
            JOptionPane.showMessageDialog(adminpage.this, "Ajouter Un Numéro De Chambre D'abord");
        }
        else {

            for(int indexRow = 0 ; indexRow < modelChambre.getRowCount() ; indexRow ++) {
                Object cellule = modelChambre.getValueAt(indexRow, 0);
                if(cellule.toString().equals(jTextField1.getText().toString())) {
                    numeroExiste = true;
                    break;
                }
            }
            if(!numeroExiste) {
                Chambre.AjouterUneChambre(administrateur ,jTextField1.getText() , jComboBox1.getSelectedItem().toString() , jComboBox2.getSelectedItem().toString());
                modelChambre.insertRow(tblchambre.getRowCount(), new Object[]{
                    jTextField1.getText(),
                    jComboBox1.getSelectedItem(),
                    jComboBox2.getSelectedItem(),

                });

            }
            else {
                JOptionPane.showMessageDialog(null, "Ce Numéro De Chambre Existe Déja");
            }
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndel;
    private javax.swing.JPanel gestiondechambre;
    private javax.swing.JPanel gestiondereservation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblchambre;
    // End of variables declaration//GEN-END:variables


     
}
